gaps:
  inner_gap: 20
  outer_gap: 20

general:
  show_floating_on_top: false
  cursor_follows_focus: false # Want to use this but it's broken
  floating_window_move_amount: "5%"
  focus_border_color: "#77A8D9FF"

bar:
  height: "30px"
  position: "top"
  opacity: 1.0
  background: "#1F2430"
  foreground: "#FAFAFA"
  font_family: "FiraCode Nerd Font Mono"
  font_size: "16px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#20242cc4"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      time_formatting: "HH:mm ddd MMM d"
      margin: "0 0 0 10px"

workspaces:
  - name: "2"
    display_name: "2:web"
    bind_to_monitor: 2
  - name: "4"
    display_name: "4:media"
    bind_to_monitor: 2
  - name: "6"
    display_name: "6:misc"
    bind_to_monitor: 2
  - name: "8"
    display_name: "8:twitch"
    bind_to_monitor: 2
  - name: "1"
    display_name: "1:main"
    bind_to_monitor: 1
  - name: "3"
    display_name: "3:files"
    bind_to_monitor: 1
  - name: "5"
    display_name: "5:web"
    bind_to_monitor: 1
  - name: "7"
    display_name: "7:settings"
    bind_to_monitor: 1
  - name: "9"
    display_name: "9:games"
    bind_to_monitor: 1

window_rules:
  # --- Ignore rules ---
  - command: "ignore" # Misc
    match_process_name: "/Taskmgr|BCUninstaller|ArgusMonitor|ScreenClippingHost|OpenWith|parsecd/"
  - command: "ignore"
    match_class_name: "/#32770|operationstatuswindow|RAIL_WINDOW|AutoHotKeyGUI/" # System dialogs and WSL windows
  - command: "ignore" # Games
    match_process_name: "/fsd-win64-shipping|RocketLeague|acsW|BONELAB_Steam_Windows64|csgo|bfv|bf4|bf1/"
  - command: "ignore"
    match_title: "/Minecraft.*/"
  - command: "ignore"
    match_class_name: "/GameEngineMainWindow|ThunderRT6FormDC/"
  - command: "ignore" # Applications
    match_process_name: "/Flow.Launcher|Unity|RealHeadMotionAssettoCorsaCompetizione|content manager/"
  - command: "ignore" # Steam menu
    match_class_name: "SDL_app"
    match_title: "Menu"

  # --- Floating rules ---
  - command: "set floating"
    match_process_name: "/AutoHotkeyUX|devenv/"
  - command: "set floating"
    match_class_name: "/SDL_app|UnityWndClass/"
  - command: "set floating"
    match_process_name: "MultiMC"
  - command: "set floating"
    match_title: "Visual Studio Installer"
  - command: "set floating"
    match_process_name: "chatterino"
    match_title: "/.*Usercard.*|Chatterino Settings|Reply Thread.*|.*select stream quality.*|Emotes.*/"

  # --- Tiling rules ---
  - command: "set tiling"
    match_process_name: "mpv"

  # --- Border resize rules ---
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "/steam|mpv|OneCommander/"

  # --- Workspace move rules ---
  # Games
  - commands: ["move to workspace 9", "focus workspace 9"]
    match_process_name: "/steam|MultiMC/"
  # Files
  - commands: ["move to workspace 3", "focus workspace 3"]
    match_process_name: "/OneCommander/"
  # Social
  - commands: ["move to workspace 4", "focus workspace 4"]
    match_process_name: "/Discord|Spotify/"
  # Twitch
  - commands: ["move to workspace 8", "focus workspace 8", "resize borders 20px 13px 13px -7px"]
    match_process_name: "/chatterino/"
  - commands: ["move to workspace 8", "focus workspace 8", "move left", "resize borders 20px 13px 13px 13px", "set width 81%"]
    match_process_name: "mpv"
    match_title: "/twitch.*/"
  # Settings
  - commands: ["move to workspace 7", "focus workspace 7"]
    match_process_name: "/ApplicationFrameHost|nvcplui|mmc/"
  - commands: ["move to workspace 7", "focus workspace 7"]
    match_process_name: "explorer"
    match_title: "/Control Panel.*/"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        binding: "H"
      - command: "resize width +2%"
        binding: "L"
      - command: "resize height +2%"
        binding: "K"
      - command: "resize height -2%"
        binding: "J"
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

  - name: "programs"
    keybindings:
      - commands: ["exec 'C:\\Users\\Joshua\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Scoop Apps\\Everything.lnk'", "binding mode none"]
        binding: "E"
      - commands: ["exec 'C:\\Users\\Joshua\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Scoop Apps\\OneCommander.lnk'", "binding mode none"]
        binding: "O"
      - commands: ["exec 'C:\\Users\\Joshua\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Scoop Apps\\Neovim.lnk'", "binding mode none"]
        binding: "N"
      - commands: ["exec 'C:\\Users\\Joshua\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Scoop Apps\\Alacritty.lnk'", "binding mode none"]
        binding: "Enter"

      # Press escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape"]

  - name: "disabled"
    keybindings:
      - command: "binding mode none"
        binding: "Escape"

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    binding: "LMenu+H"
  - command: "focus right"
    binding: "LMenu+L"
  - command: "focus up"
    binding: "LMenu+K"
  - command: "focus down"
    binding: "LMenu+J"

  # Move focused window in a given direction.
  - command: "move left"
    binding: "LMenu+Shift+H"
  - command: "move right"
    binding: "LMenu+Shift+L"
  - command: "move up"
    binding: "LMenu+Shift+K"
  - command: "move down"
    binding: "LMenu+Shift+J"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "LMenu+R"

  - command: "binding mode programs"
    binding: "LMenu+O"

  # Disable bindings
  - command: "binding mode disabled"
    binding: "LMenu+Escape"

  # Toggle tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "LMenu+X"

  # Change focus between floating / tiling windows.
  - command: "toggle focus mode"
    binding: "LMenu+F"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "LMenu+C"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "LMenu+E"

  # Disable window borders
  - command: "resize borders 20px"
    binding: "LMenu+B"

  # Enable window borders
  - command: "resize borders 0px"
    binding: "LMenu+Shift+B"

  # Set size of twitch player
  - command: "set width 81%"
    binding: "LMenu+Shift+T"

  # Minimize focused window.
  - command: "set minimized"
    binding: "LMenu+M"

  # Close focused window.
  - command: "close"
    binding: "LMenu+W"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "LMenu+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "LMenu+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Firefox.lnk'"
    binding: "LMenu+Back"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "LMenu+N"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    bindings: ["LMenu+Right", "XButton1"]
  - command: "focus workspace prev"
    bindings: ["LMenu+Left", "XButton2"]

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "LMenu+1"
  - command: "focus workspace 2"
    binding: "LMenu+2"
  - command: "focus workspace 3"
    binding: "LMenu+3"
  - command: "focus workspace 4"
    binding: "LMenu+4"
  - command: "focus workspace 5"
    binding: "LMenu+5"
  - command: "focus workspace 6"
    binding: "LMenu+6"
  - command: "focus workspace 7"
    binding: "LMenu+7"
  - command: "focus workspace 8"
    binding: "LMenu+8"
  - command: "focus workspace 9"
    binding: "LMenu+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "LMenu+Shift+A"
  - command: "move workspace right"
    binding: "LMenu+Shift+F"
  - command: "move workspace up"
    binding: "LMenu+Shift+D"
  - command: "move workspace down"
    binding: "LMenu+Shift+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "LMenu+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "LMenu+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "LMenu+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "LMenu+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "LMenu+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "LMenu+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 4"]
    binding: "LMenu+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 5"]
    binding: "LMenu+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 6"]
    binding: "LMenu+Shift+9"

    # Move focused window to a workspace without focusing workspace
  - command: "move to workspace 1"
    binding: "LMenu+Shift+Control+1"
  - command: "move to workspace 2"
    binding: "LMenu+Shift+Control+2"
  - command: "move to workspace 3"
    binding: "LMenu+Shift+Control+3"
  - command: "move to workspace 4"
    binding: "LMenu+Shift+Control+4"
  - command: "move to workspace 5"
    binding: "LMenu+Shift+Control+5"
  - command: "move to workspace 6"
    binding: "LMenu+Shift+Control+6"
  - command: "move to workspace 7"
    binding: "LMenu+Shift+Control+7"
  - command: "move to workspace 8"
    binding: "LMenu+Shift+Control+8"
  - command: "move to workspace 9"
    binding: "LMenu+Shift+Control+9"
