#!/usr/bin/zsh

# general
alias dotfiles='/usr/bin/git --git-dir=$HOME/.config/.dotfiles --work-tree=$HOME/.config'
alias please='sudo $(fc -ln -1)'
alias reload='exec zsh'
alias bootwindows='systemctl reboot --boot-loader-entry=windows.conf'
alias bootbios='systemctl reboot --firmware-setup'

# exa
if (( $+commands[exa] )); then
    alias la='exa -a --icons'
    alias ll='exa -la --icons'
    alias ls='exa --icons'
    alias tree='exa --tree'
fi

# lazygit
if (( $+commands[lazygit] )); then
    alias dotfileslazy='lazygit --git-dir=$HOME/.config/.dotfiles --work-tree=$HOME/.config'
fi
