#!/usr/bin/zsh

alias la='exa -a --icons'
alias ll='exa -la --icons'
alias ls='exa --icons'
alias tree='exa --tree'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.config/.dotfiles --work-tree=$HOME/.config'
alias please='sudo $(fc -ln -1)'
alias reload='exec zsh'
