#!/usr/bin/zsh

# initialise completions with zsh's compinit
autoload -Uz compinit && compinit

# fzf completion
source_if_exists /usr/share/fzf/key-bindings.zsh
source_if_exists /usr/share/fzf/completion.zsh
